spring.application.name=personal-finance-platform
#Spring Boot not to auto-configure any database ? it skips the DB setup and starts the app normally.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

